const FETCH_QUOTES = 'FETCH_QUOTES';
const GET_QUOTES = 'GET_QUOTES';
const LOAD_MORE = 'LOAD_MORE';
const RANDOM = 'RANDOM';
const QUOTE_ERROR = 'QUOTE_ERROR';

export {
  GET_QUOTES, LOAD_MORE, RANDOM, QUOTE_ERROR, FETCH_QUOTES,
};
